### ISSUE TITLE
iSCSI target alias is not registered

### ISSUE THREAD

**Issue by yu-murai** [open-iscsi/target-isns#48]
I found the issue about 'target-isns' that is NOT include function via RFC 4171.
When I checked the target status on the isns server(Windows 2016) after registered iscsi target, and I realized target alias is blank.
Accroding to RFC 4171, isns server must be implemented that. Please check the following section.

4.1.1.  Required Attributes for Support of iSCSI
<https://tools.ietf.org/html/rfc4171>

For supporting target-isns made via RFC 4171, improvement is necessary.

**Comment by gonzoleeman** [comment]
So you are saying you tried to register an Alias, and it did not work?

Can you explain the steps you took, so that I might reproduce this issue? Screen shots would also be helpful.

The code makes it look like the Alias attribute *is* supported for Storage Nodes.

**Comment by yu-murai** [comment]
Hi gonzoleeman

Thank you for your quick reply.

I apologize I didn't provide enough information. Please check the below operation.

I used target-isns binary for building system according to documantetion (testing.md).
I read 'Testing with fake iSCSI configurations' in this document, so I just tried,

Step1:mkdir -p fake-iscsi-path/iqn.2018-01.org.example:disk1
Step2:mkdir -p fake-iscsi-path/iqn.2018-01.org.example:disk1/tpgt_1
Step3:mkdir -p fake-iscsi-path/iqn.2018-01.org.example:disk1/tpgt_1/np
Step4:mkdir -p fake-iscsi-path/iqn.2018-01.org.example:disk1/tpgt_1/np/0.0.0.0:3260
Step5:echo 1 > fake-iscsi-path/iqn.2018-01.org.example:disk1/tpgt_1/enable
Step6:mkdir -p fake-iscsi-path/iqn.2018-01.org.example:disk1/tpgt_1/param
Step7:mkdir -p fake-iscsi-path/iqn.2018-01.org.example:disk1/tpgt_1/param/alias.example

After that, I executed,

Step8:./src/target-isns --isns-server 192.168.16.253 --debug --configfs-iscsi-path fake-iscsi-path/

Note:iSNS server is assigned a local IP address.

And I got the screenshot for you, please check the attached.

If I am taking a miss operation, please let me know.

Thanks,

**Comment by cvubrugier** [comment]
@yu-murai, thank you for reporting this issue.

The target alias parameter is not read by target-isns and thus not reported to the iSNS server. I plan to implement support it but cannot say when it will be done.
Moreover, the [testing documentation](testing.md) will have to be updated to describe how to set the target alias parameter.

**Comment by yu-murai** [comment]
Hi @cvubrugier 
Thank you for your reply.
I am looking forward to be implemented target alias parameter and I am sure it will be support in some day.(not decide now)
Hopefully, I would like to use this parameter until July 2019.
When this issue will be progressed, I can support the test(debug) when you upload the patch on githab if you want.

Thanks

**Comment by cvubrugier** [comment]
Hi @yu-murai,

I have pushed a branch named [register-alias](https://github.com/open-iscsi/target-isns/tree/register-alias) that contains a patch to register the iSCSI target alias to the iSNS server. I have tested that it works with Open-iSNS but I have not tested with the Microsoft iSNS server.

If you test with a fake iSCSI configuration, be sure to create a `TargetAlias` parameter (see the [testing.md](https://github.com/open-iscsi/target-isns/blob/register-alias/documentation/testing.md) document in the register-alias branch).

**Comment by yu-murai** [comment]
Hi @cvubrugier 

Thank you for your quick push. And I am sorry for delay response.
I tested with the Microsoft iSNS server(Windows 2016 and Windows 2012) with [register-alias](https://github.com/open-iscsi/target-isns/tree/register-alias) instead of you. It works I expected. Please check attached.(Sorry in Japanese)

![image](https://user-images.githubusercontent.com/48705155/57924198-78b9e680-78df-11e9-9390-2b2537520445.png)

Could you please tell me, when would you push this patch to master branch?

Thanks,

**Comment by gonzoleeman** [comment]
I will push this Monday since I’m out of town now. 

--
Lee-Man Duncan

**Comment by yu-murai** [comment]
Hi @gonzoleeman @cvubrugier 

Thank you for your support. I confirmed this issue was merged to master branch.
After this, do you have a plan to make a new release branch?(e.g. V 0.6.6)

**Comment by cvubrugier** [comment]
Hi @yu-murai,

I plan to make a new release tonight. target-isns does not see much changes those days but receives some fixes from time to time. It's important to release these fixes to our users.

**Comment by yu-murai** [comment]
Hi @cvubrugier 

Thank you for your report. I got it.

**Comment by mostlybrian** [comment]
Hi.  I _think_ found a _tiny_ bug in the implementation, the call to target_get_alias in isns_target_register should take tgt as the parameter (not target).  Without this all targets get registered with the same alias.

Thanks for implementing this feature!

**Comment by cvubrugier** [comment]
Nice catch @mostlybrian!
Could you contribute a patch, please? I would like you to get credit for what you found.

Thanks!
